export LC_ALL=en_US.UTF-8

# For compilers to find node@20
export LDFLAGS="-L$(brew --prefix)/opt/node@20/lib"
export CPPFLAGS="-I$(brew --prefix)/opt/node@20/include"

# Add .NET Core SDK tools
export PATH="$PATH:$HOME/.dotnet/tools"

# Added by Toolbox App
export PATH="$PATH:$HOME/Library/Application Support/JetBrains/Toolbox/scripts"